export const qb5QuesArr = [
  "Understands their duty to look after their own health and safety and the health and safety of their team",
  "Shows their team a sense of personal and collective responsibility and commitment for health and safety",
  "Supports their Manager implementing the LOR H&S management system [inc policy and procedures]",
  "Promotes open communication on all H&S matters, involves team members in drawing up planned methods, and provides advice and support to team members in complex/ demanding situations",
  "Knows the principles of the Laing O’Rourke Safety Management System (SMS) and understands that they play a key part in helping the team and their Manager to comply with its requirements",
  "Knows how to work to Risk Assessments, Method Statements and Visual Task Sheets and brief the team in an engaging manner",
  "Knows to pause operations whenever circumstances change, review risk assessment and update Method Statement Task Sheets with the Responsible Manager and brief the team before re-starting",
  "Knows and understands key H&S regulations which affect site based work, and how to comply with them. Seeks advice when unsure",
  "Knows the importance of the effective maintenance of plant, tools and equipment and how to report any defects",
  "Is aware of the requirements of their safe system of work and where appropriate for confined space, excavation and hot works permits ",
  "Understands COSHH hazard symbols and what risk control measures are required for each",
  "Has good understanding of PPE requirements and how it is used and stored ",
  "Has the ability to search, find and retrieve H&S guidance and templates from the iGMS",
  "Is able to contribute to the preparation of Risk Assessments, Method Statements, Task Sheets with the team and the Responsible Manager",
  "Is able to assess the risks inherent in an operation, and can help plan and implement a safe system to work",
  "Is able to keep H&S records relevant to the work of the team they supervise, including records of Briefings and Tool Box talks delivered",
  "Is able to articualte the Next Gear approach to H&S to their team including Next Gear tools",
  "Has attended the LOR Occupational Health e-Learning modules and understands the relevance to their role",
  "Understands what the main Occupational health risks are and their source [i.e. HAV, Noise, Dust, MSD]",
  "Understands the legal requirements related to Occupational Health Risks and ensures RAMS, SSoW, VTS include suitable and sufficient risk control measures to mitigate the risk.",
  "Understands their role in minimising risk exposure to their workers by finding a lower risk solution [i.e. applies the risk hierachy]",
  "Ensures all necessary SSoW involving OH Risk Controls are closely followed [i.e. Vibration trigger times etc] and where appropriate, restrictions applied",
  "Understands the importance of Health Surveillance for their team and the need to monitor for poor OH health symptoms [e.g. tingling fingers] and refer all concerned to the LOR Occupational Health team",
  "Regularly talks to their team and raises the awareness of OH risks in the workplace",
  "Actively engages in Occupational health campaigns and leads on the implementation of good practice / the LOR leading standards",
  "Can demonstrate effective supervision of works involving Occupational Health Risks",
  "Can monitor and advise Sub Contractors on OH Risk Management improvement suggestions ",
  "Understands the high potential risks and potential hazards within their work scope and takes approriate steps to ensure they are safely managed",
  "Is able to contribute to the preparation of Risk Assessments, Method Statements, and Visual Task Sheets with the  Responsible Manager and involves their team",
  "Is able to carry out engaging and collective [2-Way] briefings [VTS, DABs, TBTs etc] in a manner appropriate to the task and the team",
  "Is able to look beyond their immediate work area and identify wider risks",
  "Is able to implement approved and recorded risk mitigation measures within their area of responsibility",
  "Works with other Supervisors and their Manager to implement consistent best practice / leading standards",
  "Has attended the Next Gear Introduction training and understands the main tools it provides and how to use them in the workplace [Collective Insight, Planned vs Actual, Fatal & Severe Risk Review]",
  "Has lead / facilitated delivery of at least one of each of the Next Gear Tools [Collective Insight, Planned vs Actual, Fatal & Severe Risk Review]",
  "Understands the companies approach to Wellbeing",
  "Knows where to access Wellbeing  services and can signpost individuals to them",
  "Proactively applies principles from the Energy Project and wellbeing to support personal sustainability and performance in their teams",
  "Role models capacity management and wellbeing and creates an environment to support this in their team",
];

export const qb1QuesArr = [
  "Briefs the team about standards and objectives and generates strong pride in safely achieving the right quality",
  "Successfully adapts different approaches to get the best from the team",
  "Has a listening and questioning approach",
  "Gives clear directives and requests",
  "Is able to delegate effectively, considers individuals capabilities before assigning tasks",
  "Is objective and fair in treatment of employees",
  "Gives timely and constructive feedback to individuals on good and poor performance",
  "Regularly reviews each individuals progress on tasks and records the results",
  "Refers to line manager for support with action plans for high and poor performing employees",
  "Knows the roles and responsibilities of team members and ensures that they deliver them",
  "Coaches, mentors and supports team members when needed",
  "Motivates and develops others to improve performance",
  "Considers team member’s management styles when reviewing their performance",
  "Uses their knowledge of sequencing and work scheduling to ensure effective use of resources",
  "Owns their own development",
  "Can complete a Personal Development Plan",
  "Is familiar with preferred skills and qualities of team members and working supervisors",
  "Works with their manager to identify team members with potential for promotion",
  "Acts with integrity and objectivity when considering candidates",
  " Able to diffuse potential conflict in the workplace",
  "Handles poor performance or misconduct issues fairly and in accordance with the key steps of the company procedures",
  " Knows how to actively monitor and takes steps to deal with potential conflict situations before it develops",
  "Works effectively as a team member and is able to manage a small team",
  "Manages team members and supervisors well",
  "Briefs the team about standards and objectives, and generates strong pride in safely achieving the right quality",
  "Works with the Trade Supervisor and General Foreman to help achieve best team",
  "Recognises good and bad team characteristics and takes action to maintain and improve team performance",
  "Knows the importance and potential of successful team working and the positive effect this has on safety, quality and production",
  "Creates successful teams by recognising and achieving the right mix and balance of skills and responsibilities",
  "Understands the development requirements for a team member and a Working Supervisor",
  "Implements successful team working principles within their own team and with other teams",
  "Works with their manager to review talent within the team on a systematic, objective and fair basis",
  "Uses objective and fair methods to recognise team members who have talent and potential to develop into supervisory roles",
  "Provides suitable on-the-job coaching, mentoring, support, and advice to retain and develop talented individuals and assist them in safely achieving the right quality",
  "Plans, resources and delivers their teams weekly objectives safely to the right quality and on time",
  "Keeps others regulary updated as neccessary about current plans",
  " Plans contingencies for forseeable changes and takes preventive action where possible",
  "Understands the need to make time to help others to plan and deliver their work",
  "Provide clear direction and leadership to the team",
  "Applies standards consistently and fairly across their team",
  "Is comfortable leading and taking responsibility for their team and area of work",
  "Makes well considered decisions and informs team members quickly",
  "Adapts to change and shows resilience when unforeseen problems occur",
  "Shows calmness, enthusiasm and assurance in delivering briefings and decisions to the team",
  "Understands the importance of clarifying roles and responsibilities for all team members",
  "Knows how to gather information required for the work and brief to their team",
  "Demonstrates self-motivation",
  "Builds productive relationships with their manager and other #stakeholders",
  "Knows about available methods of communication, where to access them, and how to use them",
  "Understands the importance of regular progress reviews against objectives",
  "Can address a group of up to 30 and achieve full engagement and support for the content",
  "Communicates objectively with the whole team through briefings, tool box talks, one-to-ones, and establishes an appropriate relationship with each team member",
];
