// Healt, Safety & Wellbeing
export const qb5QuesArr = [
  "Understands their duty to look after their own health and safety and the health and safety of their team",
  "Shows their team a sense of personal and collective responsibility and commitment for health and safety",
  "Supports their Manager implementing the LOR H&S management system [inc policy and procedures]",
  "Promotes open communication on all H&S matters, involves team members in drawing up planned methods, and provides advice and support to team members in complex/ demanding situations",
  "Knows the principles of the Laing O’Rourke Safety Management System (SMS) and understands that they play a key part in helping the team and their Manager to comply with its requirements",
  "Knows how to work to Risk Assessments, Method Statements and Visual Task Sheets and brief the team in an engaging manner",
  "Knows to pause operations whenever circumstances change, review risk assessment and update Method Statement Task Sheets with the Responsible Manager and brief the team before re-starting",
  "Knows and understands key H&S regulations which affect site based work, and how to comply with them. Seeks advice when unsure",
  "Knows the importance of the effective maintenance of plant, tools and equipment and how to report any defects",
  "Is aware of the requirements of their safe system of work and where appropriate for confined space, excavation and hot works permits ",
  "Understands COSHH hazard symbols and what risk control measures are required for each",
  "Has good understanding of PPE requirements and how it is used and stored ",
  "Has the ability to search, find and retrieve H&S guidance and templates from the iGMS",
  "Is able to contribute to the preparation of Risk Assessments, Method Statements, Task Sheets with the team and the Responsible Manager",
  "Is able to assess the risks inherent in an operation, and can help plan and implement a safe system to work",
  "Is able to keep H&S records relevant to the work of the team they supervise, including records of Briefings and Tool Box talks delivered",
  "Is able to articualte the Next Gear approach to H&S to their team including Next Gear tools",
  "Has attended the LOR Occupational Health e-Learning modules and understands the relevance to their role",
  "Understands what the main Occupational health risks are and their source [i.e. HAV, Noise, Dust, MSD]",
  "Understands the legal requirements related to Occupational Health Risks and ensures RAMS, SSoW, VTS include suitable and sufficient risk control measures to mitigate the risk.",
  "Understands their role in minimising risk exposure to their workers by finding a lower risk solution [i.e. applies the risk hierachy]",
  "Ensures all necessary SSoW involving OH Risk Controls are closely followed [i.e. Vibration trigger times etc] and where appropriate, restrictions applied",
  "Understands the importance of Health Surveillance for their team and the need to monitor for poor OH health symptoms [e.g. tingling fingers] and refer all concerned to the LOR Occupational Health team",
  "Regularly talks to their team and raises the awareness of OH risks in the workplace",
  "Actively engages in Occupational health campaigns and leads on the implementation of good practice / the LOR leading standards",
  "Can demonstrate effective supervision of works involving Occupational Health Risks",
  "Can monitor and advise Sub Contractors on OH Risk Management improvement suggestions ",
  "Understands the high potential risks and potential hazards within their work scope and takes approriate steps to ensure they are safely managed",
  "Is able to contribute to the preparation of Risk Assessments, Method Statements, and Visual Task Sheets with the  Responsible Manager and involves their team",
  "Is able to carry out engaging and collective [2-Way] briefings [VTS, DABs, TBTs etc] in a manner appropriate to the task and the team",
  "Is able to look beyond their immediate work area and identify wider risks",
  "Is able to implement approved and recorded risk mitigation measures within their area of responsibility",
  "Works with other Supervisors and their Manager to implement consistent best practice / leading standards",
  "Has attended the Next Gear Introduction training and understands the main tools it provides and how to use them in the workplace [Collective Insight, Planned vs Actual, Fatal & Severe Risk Review]",
  "Has lead / facilitated delivery of at least one of each of the Next Gear Tools [Collective Insight, Planned vs Actual, Fatal & Severe Risk Review]",
  "Understands the companies approach to Wellbeing",
  "Knows where to access Wellbeing  services and can signpost individuals to them",
  "Proactively applies principles from the Energy Project and wellbeing to support personal sustainability and performance in their teams",
  "Role models capacity management and wellbeing and creates an environment to support this in their team",
];

// Leadership & Management
export const qb1QuesArr = [
  "Briefs the team about standards and objectives and generates strong pride in safely achieving the right quality",
  "Successfully adapts different approaches to get the best from the team",
  "Has a listening and questioning approach",
  "Gives clear directives and requests",
  "Is able to delegate effectively, considers individuals capabilities before assigning tasks",
  "Is objective and fair in treatment of employees",
  "Gives timely and constructive feedback to individuals on good and poor performance",
  "Regularly reviews each individuals progress on tasks and records the results",
  "Refers to line manager for support with action plans for high and poor performing employees",
  "Knows the roles and responsibilities of team members and ensures that they deliver them",
  "Coaches, mentors and supports team members when needed",
  "Motivates and develops others to improve performance",
  "Considers team member’s management styles when reviewing their performance",
  "Uses their knowledge of sequencing and work scheduling to ensure effective use of resources",
  "Owns their own development",
  "Can complete a Personal Development Plan",
  "Is familiar with preferred skills and qualities of team members and working supervisors",
  "Works with their manager to identify team members with potential for promotion",
  "Acts with integrity and objectivity when considering candidates",
  " Able to diffuse potential conflict in the workplace",
  "Handles poor performance or misconduct issues fairly and in accordance with the key steps of the company procedures",
  " Knows how to actively monitor and takes steps to deal with potential conflict situations before it develops",
  "Works effectively as a team member and is able to manage a small team",
  "Manages team members and supervisors well",
  "Briefs the team about standards and objectives, and generates strong pride in safely achieving the right quality",
  "Works with the Trade Supervisor and General Foreman to help achieve best team",
  "Recognises good and bad team characteristics and takes action to maintain and improve team performance",
  "Knows the importance and potential of successful team working and the positive effect this has on safety, quality and production",
  "Creates successful teams by recognising and achieving the right mix and balance of skills and responsibilities",
  "Understands the development requirements for a team member and a Working Supervisor",
  "Implements successful team working principles within their own team and with other teams",
  "Works with their manager to review talent within the team on a systematic, objective and fair basis",
  "Uses objective and fair methods to recognise team members who have talent and potential to develop into supervisory roles",
  "Provides suitable on-the-job coaching, mentoring, support, and advice to retain and develop talented individuals and assist them in safely achieving the right quality",
  "Plans, resources and delivers their teams weekly objectives safely to the right quality and on time",
  "Keeps others regulary updated as neccessary about current plans",
  " Plans contingencies for forseeable changes and takes preventive action where possible",
  "Understands the need to make time to help others to plan and deliver their work",
  "Provide clear direction and leadership to the team",
  "Applies standards consistently and fairly across their team",
  "Is comfortable leading and taking responsibility for their team and area of work",
  "Makes well considered decisions and informs team members quickly",
  "Adapts to change and shows resilience when unforeseen problems occur",
  "Shows calmness, enthusiasm and assurance in delivering briefings and decisions to the team",
  "Understands the importance of clarifying roles and responsibilities for all team members",
  "Knows how to gather information required for the work and brief to their team",
  "Demonstrates self-motivation",
  "Builds productive relationships with their manager and other #stakeholders",
  "Knows about available methods of communication, where to access them, and how to use them",
  "Understands the importance of regular progress reviews against objectives",
  "Can address a group of up to 30 and achieve full engagement and support for the content",
  "Communicates objectively with the whole team through briefings, tool box talks, one-to-ones, and establishes an appropriate relationship with each team member",
];

// Quality
export const qb2QuesArr = [
  "Understands what is required and can be relied upon to deliver a quality product which is right first time",
  "Completes a daily record diary",
  "Ensures that all quality control and assurance records are completed as the work proceeds",
  "Is able to use a questioning and self checking approach to minimise errors",
  "Instigates regular independent checks of correctness and accuracy",
  "Reads and undertands the specification, drawings, schedules, quality plans and procedures relevant to the work being undertaken",
  "Delivers a quality product through implementation of the quality plan",
  "Supports and drives implementation of compliance and assurance procedures and records",
  "Understands and communicates method statements to ensure the team completes the work accordingly",
  "Ensures that ITP “hold” points are correctly satisfied before work proceeds",
  "Ensures that Quality Control and Assurance Records are correctly completed and authorised as work proceeds",
  "Keeps photographic compliance records of all work which will not subsequently be visible for inspection",
  "Is fully aware of requirements and procedures for Quality Inspection and Test Plans, Method Statements, Quality Control checks, Quality Assurance and Record keeping",
  "Works with stakeholders to formulate and compile ITP’s and Method Statements which ensure compliance",
  "Knows that all works have an ITP and a Method Statement",
  "Knows what to do to ensure ITP “hold” points are released with correct quality checking, authority and records",
  "Carries out inspections of works in conjunction with Section Engineers and Primary Control Team",
  "Always corrects deficient items",
  "Helps devise improved methods which prevent reccurrence of deficient items",
  "Encourages the use of NCR’s to help improve methods and quality",
  "Ensures check sheets and ITP hold points for trade specification are signed off with the correct authority before proceeding",
  " Ensures that faults identified by inspections are recorded on NCR’s and corrected and closed out accordingly",
  "Ensures that learning from NCR’s is used to generate and improve best practice in the team",
  "Has read and understood the quality plans, processes and procedures relevant to the work being undertaken",
  " Achieves compliance with approved samples",
  "Understands requirements to achieve approved samples.Is familiar with all approved samples and benchmarks relevant to the work of their team",
  "Identifies requirements for all samples, benchmarks and approvals related to their area of work",
  "Ensures that resource is available to achieve agreed standards and continually monitors progress on compliance",
  "Knows how samples, bench marks and approvals fit into the LOR Quality Management System. Knows the levels of authority and records required for approvals. Knows resource requirements to meet the standards",
  "Work from primary grids and levels provided by the Primary Control Team to provide setting out for their team in conjunction with Section Engineers",
  "Uses a questioning and self checking approach to help minimise errors",
  "Regularly checks measuring equipment for calibration",
  "Seeks regular independent checks of correctness and accuracy",
  "Accurately takes information from a drawing, schedule or specification",
  "Uses appropriate equipment for determining dimensional accuracy",
  "Interprets and uses information from drawings and checks and cross checks the information before use",
  "Is able to obtain tolerance and dimensional control information from drawings, models and specifications",
  "Sets up and controls systematic checking of dimensional control in area of work and ensures that this fits correctly with adjacent or affected work areas and trades, including following trades",
  "Envisages how dimensional control of their area of work impinges on other trades and on the finished building/structure",
  "Stores, handles, uses, and protects materials and finished work appropriately and in line with required standards",
  "Knows requirements of the drawings, specifications and schedules, and the interface between their area of work and adjacent areas and trade",
  "Ensures compliance of any material being used with drawings, specification, schedules and the purchase order / requisition",
  "Recognises characteristics of good and bad quality in commonly used materials in both temporary and permanent applications",
  "Acquires knowledge of unusual, unfamiliar or bespoke materials before planning or implementing work methods",
  "Puts resources to work and monitors progress to remove snagging items promptly",
  "Works constructively with Quality Control and Quality Assurance team to ensure systematic recording of clearance of snags",
  "Is familiar with standard procedures for clearance of snags and the required contribution from their team",
  "Works with their manager to identify snags relevant to their trade, and to agree with their line manager the required timescale for clearance and sign off of each snag",
  "Liaises with other trades supervisors to ensure that snags are actioned in a practical trade sequence",
  "Creates snagging sheets/lists, identifies appropriate resources, determines methods to systematically clear items and agrees with line manager",
  "Identifies trends and agrees amended work methods with other Supervisors and their manager to avoid repeating ",
  "Is aware of the detailed requirements to achieve Practical Completion and Handover of their area of work, including the authorised/approved and recorded clearance of snags",
  "Is aware of the value of protection of finished work in reducing snags",
];

// Planning
export const qb3QuesArr = [
  "Addresses the overriding priority of safety and quality compliance, and avoids waste of all resources",
  "Is aware of achievable production rates for tasks on site and proactively works towards them",
  "Recognises that quality, safety, reliability, predictability and smart methods (and not simply speed of construction) all contribute to cost reduction and avoiding waste",
  "Understands the principle of a budget to build including labour plant and materials for each activity",
  "Knows how to complete allocation, time and delivery sheets for labour, plant and materials",
  "Is aware of the budget to build for each activity in the area and monitors costs on a weekly basis against that budget",
  "Makes interventions where budget is threatened",
  "Regularly identifies more economic methods of implementation and is able to introduce these in a controlled manner following correct procedures",
  "Is aware of operatives’ Terms and Conditions and CPA plant conditions of hire, and how actual costs are calculated",
  "Has knowledge of labour, plant and material costs and the range of achievable outputs",
  "Can follow an agreed and documented method of working controlling a number of employees",
  "Addresses the overriding priority of safety and quality compliance in selecting methods",
  "Knows to temporarily pause activities when circumstances change, agrees and records revised methods with their manager before re-starting",
  "Understands that different work methods are appropriate in different situations, and is familiar with a selection of commonly used methods",
  "Is able to determine the best method of working, select labour, plant and materials for their trade, assess the risks involved, prepare a method statement and an ITP, and brief the team",
  "Is familiar with the need in complex multi trade interface situations to work with other Supervisors and Managers to carefully select appropriate plant, equipment, methods and coordinated sequences",
  "Can read and understand a short term programme",
  "Works with other Supervisors, their Manager and the Planner to coordinate and agree rolling short term weekly programmes for their area of work",
  "Knows if the programmed activities achieve the short term goals to comply with the budget to build",
  "Understands logical sequencing of an operation and how activities effect each other",
  "Continuously monitors progress and intervenes where neccessary to keep on track",
  "Knows the importance of the critical path, understands sequences of work and safety and quality constraints involved",
  "Assesses daily and weekly resource needs with other Supervisors and their Manager, and agrees how resources are allocated to gangs to suit the short term programmes",
  "Carries out daily management of allocated resources, identifies constraints and unforeseen events",
  "Recognises when corrective action will require a longer period than just the current short term programme period, particularly in relation to safety and quality constraints",
];

// Engineering & Design
export const qb4QuesArr = [
  "Is able to follow Temporary Works drawings and information",
  "Respects Temporary Works with the same priority and importance as all other critical safety procedures, rules and equipment",
  "Includes Temporary Works activities in their site diary record",
  "Encourages the same respect for Temporary Works in all members of the team and leads by example",
  "Understands the critical importance of implementing Temporary Works strictly in accordance with the design and associated methods and sequences",
  "Strictly complies with all Hold Points and obtains the correct Authority in writing before proceeding",
  "Knows to temporarily pause operations when circumstances change, and to review, agree, and obtain written Authority for any changed methods or sequences from their Manager and the Temporary Works Coordinator before restarting operations",
  "Selects Temporary Works systems for “basic” solutions from a pre-designed and approved list where appropriate",
  "Works with the Temporary Works Coordinator, The Temporary Works Inspectors and the site Engineers to achieve full and certified compliance with approved temporary works designs",
  "Has a good working knowledge of Temporary Works control procedures and their role in complying with them",
  "Competently reads and implements information on models, drawings, specifications, schedules, Inspection and Test plans",
  "Checks and identifies deficiencies in the approved Construction information in advance of construction",
  "Creates/obtains benchmarks samples as required in good time, and retains them for future reference",
  "Works with other team members to obtain alternative approved designs when needed",
  "Knows who produces what information and how precedence of information is important",
  "Knows that only information which has been approved for construction by the required authorities can be used as construction information",
];

// Sustainability
export const qb6QuesArr = [
  "Has attended Site Environmental Awareness training (IEMA or similar) (*IEMA Site based environmental course in development at the moment)",
  "Has completed the ES carbon literacy module and understands basic issues of climate change and basic terminology",
  "Understands the high-level sustainability policies, strategy and commitments of the business",
  "Can discuss and talk to the team at a foundation level to help improve others' awareness of Environmental Sustainability",
  "Understands the principles of environmental management onsite and applies the appropriate controls, for example: Resource management, Waste, Materials, Energy efficiency, Water efficiency, Contaminated Land, Nuisance: Dust, emissions & odours; Lighting; Noise & vibration; Traffic management and vehicle use; Traffic management plans and reducing nuisance; The historic environment and dealing with archaeological remains, Ecology, protected species and habitat and Biodiversity, Water",
  "Is familiar with project's environmental objectives and targets and the current performance of the project",
  "Follows environmental elements of Method Statements, Task Sheets, and Visual Task Sheets e.g. waste control, noise, dust",
  "Be able to deliver carbon and energy saving actions (in line with the project's Energy Action Plan)",
  "Demonstrates a personal commitment to reducing carbon emissions onsite (by reducing fuel and electricity consumption) leading by example and empowering others to do the same",
  "Demonstrates a personal commitment to the sustainability agenda onsite (material wastage for example) leading by example and empowering others to do the same",
  "Support trials of new and emerging sustainability initiatives on projects, implement innovation and best practice",
  "Demonstrates an awareness of the additional benefits of reducing emissions onsite (improved health and wellbeing, reduced noise and air quality nuisance issues, cost benefits)",
  "Actively encourages subcontractors and suppliers working on behalf of the group to reduce their emissions and material wastage",
  "Understand when, how and who to report Environmental incidents, issues and concerns to onsite",
];

//  Digital
export const qb7QuesArr = [
  "Is able to mark up 2D models to mark with comments",
  "Knows how to include pictures and drawings into electronic DABS as well as how to use the model to communicate with team",
  "Use microsoft teams to make calls, send messages and share information ",
  "Understands and accesses regularly, the variety of digita tools and softare that are available to them to support digital project delivery",
  "Knowing how acces RAMS and task sheets and save on a device to inform activity",
  "Uses shared outlook calendars to plan and manage deliveries",
  "Is able to use One Drive in collaboration with Engineers to access and print drawings",
  "Regularly uses the SMS and extracts relevant information to support delivery ",
  "Accesses appropriate information to complete work satisfactorily and distributes appropriate documents to workforce. Maintains appropriate information for the site",
  "Has a working knowledge of the site filing system and its importance. Can identify errors and discrepancies in the information presented",
];

// Business Understanding
export const qb8QuesArr = [
  "Understands the LOR transformation strategy and knows where to access transformation updates",
  "Is able to describe the 5 enduring conditions and how their activity on site can support them",
  "Shares business updates with their team",
  "Knows the LOR values and demonstrates them to the team",
];
